version: "3.7"
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    command: tail -f /dev/null