name: Deploy Web Artifact
run-name: ${{ github.actor }} is deploying himarsh.org 🚀


on:
  push:
    branches:
      - main

jobs:
  Deploy-Website:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::830097137869:role/himarsh-org-role
          aws-region: us-east-1
          role-session-name: GithubAction
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.2"
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Bundle install
        run: |
          gem install bundler
          bundle install
      - name: Jekyll build
        run: |
          set -x
          bundle exec jekyll build --trace
      - name: Upload files to S3
        run: |
          aws s3 sync _site/ s3://himarsh.org
